### ISSUE TITLE
Unexpected EOF while looking for matching `"'

### ISSUE THREAD

**Issue by ernestkamara** [coletz/kotlin_mpp_boilerplate#4]
I tried your script and works but got the following error.

```
Already up to date.
/Users/kamara/sandbox
Root folder name (without spaces): experiments
App name: KMPExperiment
Domain: com
Company: airthings
Project name: kmp_experiment
Copying files from Touchlab's KaMP Kit
Cleaning template, this may take a while...
./create_kmp_app.sh: line 196: unexpected EOF while looking for matching `"'
./create_kmp_app.sh: line 199: syntax error: unexpected end of file
```

**Comment by coletz** [comment]
Sorry for the delay. I need to ask you some questions:
1) which OS are you using?
2) which shell are you using?
3) are you using [perl's rename](https://askubuntu.com/questions/956010/whats-the-difference-between-the-different-rename-commands)?

Thanks!

EDIT:
going to close due to inactivity
